data_split:
  n_splits: 5
  test_split_size: 0.15
features:
  clouds:
    enabled: true
    weight: 0.6
  consumption_lag_168h:
    enabled: true
    weight: 1.5
  consumption_lag_1h:
    enabled: true
    weight: 1.5
  consumption_lag_24h:
    enabled: true
    weight: 1.8
  consumption_lag_48h:
    enabled: true
    weight: 1.0
  consumption_rolling_mean_168h:
    enabled: true
    weight: 1.2
  consumption_rolling_mean_24h:
    enabled: true
    weight: 1.3
  day_of_week:
    enabled: true
    weight: 1.0
  days_from_last_holiday:
    enabled: false
    weight: 0.3
  days_to_next_holiday:
    enabled: false
    weight: 0.3
  hour:
    enabled: true
    weight: 1.0
  humidity:
    enabled: true
    weight: 0.7
  is_holiday:
    enabled: true
    weight: 1.2
  is_holiday_eve:
    enabled: false
    weight: 0.5
  is_weekend:
    enabled: true
    weight: 1.2
  month:
    enabled: true
    weight: 1.0
  precipitation:
    enabled: true
    weight: 0.8
  season:
    enabled: true
    weight: 0.8
  temperature:
    enabled: true
    weight: 1.3
  wind_speed:
    enabled: true
    weight: 0.4
model_params:
  colsample_bytree: 0.8
  eval_metric: rmse
  gamma: 0.1
  learning_rate: 0.05
  max_depth: 7
  min_child_weight: 3
  n_estimators: 500
  objective: reg:squarederror
  reg_alpha: 0.1
  reg_lambda: 1.0
  subsample: 0.8
