paths:
  raw_data: data/raw/jena_climate.csv
  processed_data: data/processed/preprocessed_data.csv
  model_dir: models/model1/
  model_file: model.keras

training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.0001
